"""
Content Parser

Converts Claude output into a ContentPackage.
"""

from atlas.models.content_package import ContentPackage


class ContentParser:

    def parse(self, mission, response):

        return ContentPackage(

            mission_id=mission.mission_id,

            title="Generated by Claude",

            hook="Generated by Claude",

            script=response,

            thumbnail_brief="Generated by Claude",

            description="Generated by Claude",

            hashtags=[],

            keywords=[],

            call_to_action="Generated by Claude",

            estimated_duration=8,

            quality_score=90

        )

