"""
Content Package
Generated by the Content Department.
"""

from dataclasses import dataclass, field


@dataclass
class ContentPackage:

    mission_id: str

    title: str

    hook: str

    script: str

    thumbnail_brief: str

    description: str

    hashtags: list = field(default_factory=list)

    keywords: list = field(default_factory=list)

    call_to_action: str = ""

    estimated_duration: int = 0

    quality_score: int = 0
