"""
Artifact Writer

Stores outputs generated by Atlas departments.
"""

from dataclasses import asdict, is_dataclass

from atlas.core.logger import Logger
from atlas.repository.mission_repository import MissionRepository


class ArtifactWriter:

    def __init__(self):

        self.repository = MissionRepository()

    def save_research(self, mission, report):

        Logger.info("Saving Research Report")

        # Save markdown report
        self.repository.save_markdown(
            mission,
            "research.md",
            report.executive_summary
        )

        # Save structured object
        if is_dataclass(report):

            self.repository.save_json(
                mission,
                "research.json",
                asdict(report)
            )

